### PR TITLE
Initial folder structure implementation

### PR DESCRIPTION
**Pull request by efrenaguilar95**
Also contains a small test page I used to make sure it is all working. Currently hidden away, but will eventually remove it once it's no longer needed.

### CODE REVIEW

**Comment by KeziahMoselle** [comment]
You wanna use module.css files ?
There is currently 3 proposals :
- x.module.css files
- CSS in JS
- Tailwind (current)

**Comment by efrenaguilar95** [comment]
Not to familiar with Tailwind, researching online tells me doing it via the "module" method allows for css component to be loaded when they are needed vs. globally. But if Tailwind can also do this, I'm fine with that. Main worry is having things as modular as possible.

**Comment by KeziahMoselle** [comment]
Making things too modular at the start can slow us down by a lot though so we need to be careful not to overmodularize everything ! That's my opininon

**Comment by efrenaguilar95** [comment]
Yeah there's definitely a balance to have there. Personally, I like having things modular early on because it helps a lot when things scale up, but maybe some others can take a look at how I structure things and see what we want.

**Pull request closed without merging**
